Solve the redefined  problem in include/arch/arm64/cpu.h
Suqier/zvm pull request #7
Opened 2022-01-07 04:36 UTC by cocoeoli

2022-01-07 06:36 UTC, Suqier commented on zephyr/include/arch/arm64/cpu.h
> +#define sysreg_ops(op0, op1, crn, crm, op2) (((op0) << 19) | ((op1) << 16) | \
In zephyr cpu.h ao not accept macro sysreg_ops. Access register see Line 148. 
Ref  link : https://stackoverflow.com/questions/68226735/arm-register-definition-s3-0-c12-c12-7

2022-01-07 06:38 UTC, Suqier commented on zephyr/include/arch/arm64/cpu.h
> +#define CPTR_EL2_TZ			(1 << 8)
Please use macro "BIT(x)" to replace "<<".

2022-01-07 06:44 UTC, Suqier commented on zephyr/include/arch/arm64/cpu.h
> +#define SYS_PMSIDR_EL1			sysreg_ops(3, 0, 9, 9, 7)
So many registers, such as PMSIDR_EL1, would not help for virtualization. 
I think it could be added when we really need it.

2022-01-07 06:44 UTC, Suqier commented on zephyr/include/arch/arm64/cpu.h
> +#define ID_AA64DFR0_MTPMU_SHIFT		48
Please add "()" out of numbers.

2022-01-07 06:52 UTC, Suqier commented on zephyr/include/arch/arm64/cpu.h
> +
Please delete all this blank in the file tail.

2022-01-07 06:52 UTC, Suqier commented on zephyr/include/arch/arm64/cpu.h.patch
> +10a11,14
Remove this file now.

2022-01-07 06:53 UTC, Suqier commented on zephyr/include/zephyr/const.h
> +/*
Copyright Risk.

2022-01-07 06:53 UTC, Suqier commented on zephyr/include/zephyr/const.h
> +
Adjust blank.

2022-01-07 06:56 UTC, Suqier requested changes
Please address these feedback.

2022-01-10 08:32 UTC, cocoeoli commented
> Please address these feedback.

OK，I have adjusted some format in cpu.h.

2022-01-10 08:35 UTC, Suqier approved these changes
AC.

2022-01-10 08:36 UTC, merged